import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Terminal, Code2, Sparkles, Copy, Check, Sliders, Layers, Bot, Cpu, Database, Server, Globe, ArrowRight, Zap, CheckCircle2 } from 'lucide-react';
import MagneticButton from '../ui/MagneticButton';
import { KineticTitle, KineticSubtitle } from '../ui/KineticText';

export default function Lab() {
  const [activeTab, setActiveTab] = useState('AI_ENGINE'); // 'AI_ENGINE', 'COMPONENT_STUDIO', 'SYSTEM_ARCH'
  const [copiedCode, setCopiedCode] = useState(false);

  // AI Simulator State
  const [selectedRole, setSelectedRole] = useState('Full-Stack Engineer');
  const [isSimulatingAI, setIsSimulatingAI] = useState(false);
  const [aiOutput, setAiOutput] = useState({
    score: 98.4,
    questions: [
      "How do you optimize server-side rendering (SSR) and hydration in Next.js App Router for sub-second LCP?",
      "Explain how you integrate Google Gemini API with Supabase Edge Functions for secure prompt pipelines.",
      "How do you architect a multi-tier RBAC system using Firebase Firestore and custom JWT claims?"
    ],
    latency: "1.8s",
    tokens: 420
  });

  // UI Component Customizer State
  const [cardTheme, setCardTheme] = useState('cyan'); // 'cyan', 'indigo', 'gold', 'emerald'
  const [glassBlur, setGlassBlur] = useState(20);
  const [glowIntensity, setGlowIntensity] = useState(0.5);
  const [borderRadius, setBorderRadius] = useState(24);

  const roleConfigs = {
    'Full-Stack Engineer': {
      score: 98.4,
      questions: [
        "How do you optimize server-side rendering (SSR) and hydration in Next.js App Router for sub-second LCP?",
        "Explain how you integrate Google Gemini API with Supabase Edge Functions for secure prompt pipelines.",
        "How do you architect a multi-tier RBAC system using Firebase Firestore and custom JWT claims?"
      ],
      latency: "1.8s",
      tokens: 420
    },
    'AI & Automation Engineer': {
      score: 99.2,
      questions: [
        "Describe your autonomous Python scraping and Gemini AI SEO generation pipeline for affiliate marketing.",
        "How do you handle rate-limiting, error fallbacks, and token budgeting when batch-processing 10,000+ AI articles?",
        "What security measures do you implement to cloak affiliate URLs and log click analytics in real time?"
      ],
      latency: "1.4s",
      tokens: 580
    },
    'UI/UX & Design Systems': {
      score: 97.8,
      questions: [
        "How do you translate complex Figma design tokens into modular Tailwind CSS variables and React components?",
        "What visual hierarchy and chromatic contrast principles do you apply to achieve 100% WCAG AAA rating?",
        "Explain your workflow for creating 50+ brand identities and scalable vector logo guidelines."
      ],
      latency: "1.2s",
      tokens: 360
    }
  };

  const handleRoleChange = (role) => {
    setSelectedRole(role);
    setIsSimulatingAI(true);
    setTimeout(() => {
      setAiOutput(roleConfigs[role]);
      setIsSimulatingAI(false);
    }, 450);
  };

  const themeColors = {
    cyan: { primary: '#00f5d4', border: 'border-cyber-cyan/40', bgGlow: 'rgba(0, 245, 212, 0.15)', text: 'text-cyber-cyan' },
    indigo: { primary: '#6366f1', border: 'border-electric-indigo/40', bgGlow: 'rgba(99, 102, 241, 0.15)', text: 'text-electric-indigo' },
    gold: { primary: '#f59e0b', border: 'border-liquid-gold/40', bgGlow: 'rgba(245, 158, 11, 0.15)', text: 'text-liquid-gold' },
    emerald: { primary: '#10b981', border: 'border-emerald-400/40', bgGlow: 'rgba(16, 185, 129, 0.15)', text: 'text-emerald-400' },
  };

  const currentTheme = themeColors[cardTheme];

  const generatedComponentCode = `// Generated by Ashik's UI/UX Engine
export function GlassCard({ title, subtitle }) {
  return (
    <div 
      className="p-6 text-white border ${currentTheme.border}"
      style={{
        backdropFilter: 'blur(${glassBlur}px)',
        borderRadius: '${borderRadius}px',
        background: '${currentTheme.bgGlow}',
        boxShadow: '0 0 30px ${currentTheme.primary}${Math.round(glowIntensity * 255).toString(16).padStart(2, '0')}'
      }}
    >
      <h3 className="font-bold text-xl">${selectedRole}</h3>
      <p className="text-slate-300 text-sm">Engineered by Md. Ashik Siddike</p>
    </div>
  );
}`;

  const copyCodeToClipboard = () => {
    navigator.clipboard.writeText(generatedComponentCode);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2500);
  };

  return (
    <section id="lab" className="relative py-28 px-4 sm:px-6 lg:px-8 bg-void border-t border-white/5 overflow-hidden">
      
      {/* Background radial glow */}
      <div className="absolute top-1/3 right-1/4 h-96 w-96 rounded-full bg-neon-purple/10 blur-[150px] pointer-events-none" />

      <motion.div
        initial={{ opacity: 0, scale: 0.92, y: 50 }}
        whileInView={{ opacity: 1, scale: 1, y: 0 }}
        viewport={{ once: false, amount: 0.2 }}
        transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
        className="mx-auto max-w-7xl relative z-10"
      >
        
        {/* Section Header */}
        <div className="text-center max-w-4xl mx-auto mb-16 flex flex-col items-center">
          <div className="inline-flex items-center gap-2 font-mono text-xs text-cyber-cyan tracking-widest uppercase mb-3 px-3.5 py-1 rounded-full glass-panel border border-white/10">
            <Cpu className="h-3.5 w-3.5" />
            <KineticSubtitle text="// 04. INTERACTIVE TECH & AI SANDBOX" />
          </div>
          <h2 className="font-display font-black text-3xl sm:text-5xl md:text-6xl tracking-tight text-white text-center w-full leading-[1.1]">
            <KineticTitle text="LIVE SYSTEM" /> <br className="hidden sm:inline" />
            <KineticTitle text="ENGINEERING & AI PLAYGROUND." delay={0.2} gradient={true} />
          </h2>
          <p className="mt-4 text-slate-300 font-light text-sm sm:text-base md:text-lg max-w-2xl mx-auto text-center leading-relaxed">
            Direct proof of technical execution. Test real-time AI resume evaluations, customize tokenized design systems, and explore production-grade system architectures.
          </p>
        </div>

        {/* Tab Switcher (Mobile Swipeable) */}
        <div className="flex justify-center mb-10 max-w-full overflow-hidden">
          <div className="inline-flex items-center p-1.5 glass-panel rounded-2xl sm:rounded-full border border-white/10 gap-1 overflow-x-auto no-scrollbar max-w-full">
            {[
              { id: 'AI_ENGINE', label: 'INTERVUEAI SIMULATOR', icon: Bot },
              { id: 'COMPONENT_STUDIO', label: 'UI COMPONENT STUDIO', icon: Code2 },
              { id: 'SYSTEM_ARCH', label: 'FULL-STACK ARCHITECTURE', icon: Server },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-2 px-4 py-2.5 rounded-full font-mono text-xs whitespace-nowrap shrink-0 transition-all ${
                  activeTab === tab.id
                    ? 'bg-gradient-to-r from-cyber-cyan to-electric-indigo text-black font-bold shadow-[0_0_20px_rgba(0,245,212,0.4)]'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                <tab.icon className="h-3.5 w-3.5" />
                <span>{tab.label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* TAB 1: IntervueAI Live Simulator */}
        {activeTab === 'AI_ENGINE' && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 30 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch"
          >
            {/* Left Controls */}
            <div className="lg:col-span-4 p-8 rounded-3xl glass-panel border border-white/15 flex flex-col justify-between space-y-6">
              <div>
                <div className="font-mono text-xs text-cyber-cyan font-bold uppercase tracking-wider mb-2">
                  // SELECT TARGET RESUME PROFILE
                </div>
                <p className="text-slate-400 text-xs font-mono mb-4">
                  Simulates Google Gemini API parsing & tailored interview challenge generation.
                </p>

                <div className="space-y-2">
                  {Object.keys(roleConfigs).map((role) => (
                    <button
                      key={role}
                      onClick={() => handleRoleChange(role)}
                      className={`w-full text-left p-3.5 rounded-xl border font-mono text-xs transition-all ${
                        selectedRole === role
                          ? 'border-cyber-cyan bg-cyber-cyan/15 text-white font-bold shadow-[0_0_15px_rgba(0,245,212,0.2)]'
                          : 'border-white/10 bg-white/5 text-slate-400 hover:text-white'
                      }`}
                    >
                      <div className="flex items-center justify-between">
                        <span>{role}</span>
                        {selectedRole === role && <span className="text-cyber-cyan">ACTIVE</span>}
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Real-time AI Metrics */}
              <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-3 font-mono text-xs">
                <div className="flex items-center justify-between">
                  <span className="text-slate-400">LLM MODEL:</span>
                  <span className="text-white font-bold">Google Gemini 1.5 Pro</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-slate-400">EVALUATION SPEED:</span>
                  <span className="text-cyber-cyan font-bold">{aiOutput.latency}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-slate-400">CONTEXT TOKENS:</span>
                  <span className="text-electric-indigo font-bold">{aiOutput.tokens} tokens</span>
                </div>
              </div>
            </div>

            {/* Right Live Stream Output */}
            <div className="lg:col-span-8 p-8 sm:p-10 rounded-3xl glass-panel border border-white/15 flex flex-col justify-between shadow-[0_20px_60px_rgba(0,0,0,0.8)] relative overflow-hidden">
              <div className="absolute top-0 right-0 p-8 font-mono text-xs text-slate-500 pointer-events-none">
                ENDPOINT: /api/v1/interview/generate
              </div>

              <div>
                <div className="flex items-center gap-3 mb-6 pb-4 border-b border-white/10">
                  <div className="h-3 w-3 rounded-full bg-red-500" />
                  <div className="h-3 w-3 rounded-full bg-yellow-500" />
                  <div className="h-3 w-3 rounded-full bg-emerald-500" />
                  <span className="font-mono text-xs text-slate-400 ml-2">
                    INTERVUEAI_KERNEL // {selectedRole.toUpperCase()}
                  </span>
                </div>

                <div className="flex items-center gap-6 mb-6">
                  <div className="p-4 rounded-2xl bg-cyber-cyan/10 border border-cyber-cyan/30 text-center min-w-[120px]">
                    <div className="font-display font-black text-3xl text-cyber-cyan">
                      {aiOutput.score}%
                    </div>
                    <div className="font-mono text-[10px] text-slate-400">Match Confidence</div>
                  </div>

                  <div>
                    <h3 className="font-display font-bold text-xl text-white">
                      Generated Interview Challenges
                    </h3>
                    <p className="font-mono text-xs text-slate-400">
                      Real-time contextual questions synthesized from applicant parameters.
                    </p>
                  </div>
                </div>

                {/* Challenges Stream */}
                <div className="space-y-3 font-mono text-xs text-slate-200">
                  {aiOutput.questions.map((q, idx) => (
                    <div
                      key={idx}
                      className="flex items-start gap-3 p-4 rounded-xl bg-white/5 border border-white/10"
                    >
                      <span className="text-cyber-cyan font-bold shrink-0">0{idx + 1}.</span>
                      <span className="leading-relaxed">{q}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="mt-8 pt-4 border-t border-white/10 flex items-center justify-between font-mono text-xs text-slate-400">
                <span>SECURITY: SUPABASE ROW-LEVEL AUTH ENABLED</span>
                <span className="text-emerald-400 font-bold">READY FOR LIVE DEMO</span>
              </div>
            </div>
          </motion.div>
        )}

        {/* TAB 2: UI Component Studio */}
        {activeTab === 'COMPONENT_STUDIO' && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 30 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch"
          >
            {/* Controls */}
            <div className="lg:col-span-5 p-8 rounded-3xl glass-panel border border-white/15 space-y-6">
              <div className="font-mono text-xs text-cyber-cyan font-bold uppercase tracking-wider">
                // DESIGN TOKEN & GLASSMORPHISM CONTROLLER
              </div>

              {/* Color Scheme */}
              <div>
                <label className="block font-mono text-xs text-slate-400 mb-2">ACCENT COLOR</label>
                <div className="grid grid-cols-4 gap-2">
                  {['cyan', 'indigo', 'gold', 'emerald'].map((c) => (
                    <button
                      key={c}
                      onClick={() => setCardTheme(c)}
                      className={`p-3 rounded-xl border font-mono text-xs capitalize transition-all ${
                        cardTheme === c
                          ? 'border-white bg-white/20 text-white font-bold'
                          : 'border-white/10 bg-white/5 text-slate-400 hover:text-white'
                      }`}
                    >
                      {c}
                    </button>
                  ))}
                </div>
              </div>

              {/* Blur Slider */}
              <div>
                <div className="flex justify-between font-mono text-xs text-slate-400 mb-1">
                  <span>BACKDROP BLUR</span>
                  <span className="text-white font-bold">{glassBlur}px</span>
                </div>
                <input
                  type="range"
                  min="5"
                  max="40"
                  value={glassBlur}
                  onChange={(e) => setGlassBlur(parseInt(e.target.value))}
                  className="w-full accent-cyber-cyan cursor-pointer"
                />
              </div>

              {/* Border Radius Slider */}
              <div>
                <div className="flex justify-between font-mono text-xs text-slate-400 mb-1">
                  <span>BORDER RADIUS</span>
                  <span className="text-white font-bold">{borderRadius}px</span>
                </div>
                <input
                  type="range"
                  min="8"
                  max="40"
                  value={borderRadius}
                  onChange={(e) => setBorderRadius(parseInt(e.target.value))}
                  className="w-full accent-cyber-cyan cursor-pointer"
                />
              </div>

              {/* Glow Slider */}
              <div>
                <div className="flex justify-between font-mono text-xs text-slate-400 mb-1">
                  <span>GLOW INTENSITY</span>
                  <span className="text-white font-bold">{Math.round(glowIntensity * 100)}%</span>
                </div>
                <input
                  type="range"
                  min="0.1"
                  max="1"
                  step="0.1"
                  value={glowIntensity}
                  onChange={(e) => setGlowIntensity(parseFloat(e.target.value))}
                  className="w-full accent-cyber-cyan cursor-pointer"
                />
              </div>
            </div>

            {/* Live Render & React Code Output */}
            <div className="lg:col-span-7 p-8 sm:p-10 rounded-3xl glass-panel border border-white/15 flex flex-col justify-between">
              <div>
                <div className="font-mono text-xs text-slate-400 mb-4">// REAL-TIME COMPONENT PREVIEW</div>
                
                {/* Rendered Preview Card */}
                <div
                  className={`p-8 border transition-all duration-300 ${currentTheme.border}`}
                  style={{
                    backdropFilter: `blur(${glassBlur}px)`,
                    borderRadius: `${borderRadius}px`,
                    backgroundColor: currentTheme.bgGlow,
                    boxShadow: `0 0 40px ${currentTheme.primary}${Math.round(glowIntensity * 255).toString(16).padStart(2, '0')}`,
                  }}
                >
                  <div className="flex items-center justify-between mb-4">
                    <span className="px-3 py-1 rounded-full bg-black/40 text-[10px] font-mono text-white border border-white/10">
                      LIVE_TOKEN
                    </span>
                    <Sparkles className={`h-4 w-4 ${currentTheme.text}`} />
                  </div>
                  <h3 className="font-display font-black text-2xl text-white">
                    MD. ASHIK SIDDIKE
                  </h3>
                  <p className="text-sm font-mono text-slate-300 mt-1">
                    Full-Stack Developer & UI/UX Graphic Designer
                  </p>
                </div>

                {/* Generated React Code Snippet */}
                <div className="mt-6 rounded-2xl bg-black/60 p-4 border border-white/10 font-mono text-xs text-slate-300 overflow-x-auto">
                  <pre className="text-cyber-cyan">{generatedComponentCode}</pre>
                </div>
              </div>

              {/* Copy Code Button */}
              <div className="mt-6 pt-4 border-t border-white/10 flex items-center justify-between">
                <span className="font-mono text-xs text-slate-400">FRAMEWORK: TAILWIND CSS & REACT 19</span>
                <button
                  onClick={copyCodeToClipboard}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-cyber-cyan text-black font-display font-bold text-xs hover:scale-105 transition-transform"
                >
                  {copiedCode ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  <span>{copiedCode ? 'COPIED REACT CODE!' : 'COPY COMPONENT CODE'}</span>
                </button>
              </div>
            </div>
          </motion.div>
        )}

        {/* TAB 3: Full-Stack Architecture Graph */}
        {activeTab === 'SYSTEM_ARCH' && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 30 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="p-8 sm:p-12 rounded-3xl glass-panel border border-white/15"
          >
            <div className="text-center max-w-2xl mx-auto mb-10">
              <h3 className="font-display font-bold text-2xl sm:text-3xl text-white">
                IntervueAI & Affiliate Automation Architecture
              </h3>
              <p className="font-mono text-xs sm:text-sm text-slate-400 mt-2">
                Multi-tier production stack engineered for sub-second latency, RBAC security, and automated AI orchestration.
              </p>
            </div>

            {/* Architecture Flow Diagram */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
              {[
                {
                  step: "01. CLIENT FRONTEND",
                  title: "Next.js & React 19",
                  desc: "TypeScript, Tailwind CSS, GSAP Motion, Server Components, PDF parsing pipeline",
                  color: "from-cyan-500/20 to-blue-500/20",
                  border: "border-cyber-cyan/40",
                  tech: "Next.js / TS / Tailwind"
                },
                {
                  step: "02. AUTH & STATE",
                  title: "Supabase & Firebase",
                  desc: "Row-Level Security (RLS), OAuth, Firestore real-time sync, and token management",
                  color: "from-indigo-500/20 to-purple-500/20",
                  border: "border-electric-indigo/40",
                  tech: "Supabase / Firebase RBAC"
                },
                {
                  step: "03. BACKEND & SCRAPING",
                  title: "Node.js & Python",
                  desc: "REST APIs, Express.js microservices, autonomous web scraping & auto-blogging engine",
                  color: "from-purple-500/20 to-pink-500/20",
                  border: "border-neon-purple/40",
                  tech: "Node.js / Python / Vercel"
                },
                {
                  step: "04. AI INFERENCE",
                  title: "Google Gemini API",
                  desc: "Sub-2s resume evaluation, contextual question synthesis, and SEO article generation",
                  color: "from-amber-500/20 to-emerald-500/20",
                  border: "border-liquid-gold/40",
                  tech: "Gemini 1.5 Pro / LLM Prompting"
                }
              ].map((node, i) => (
                <div
                  key={i}
                  className={`p-6 rounded-2xl glass-panel border ${node.border} flex flex-col justify-between`}
                >
                  <div>
                    <span className="font-mono text-[10px] text-cyber-cyan font-bold block mb-2">
                      {node.step}
                    </span>
                    <h4 className="font-display font-bold text-lg text-white mb-2">
                      {node.title}
                    </h4>
                    <p className="text-xs text-slate-300 font-light leading-relaxed mb-4">
                      {node.desc}
                    </p>
                  </div>
                  <div className="pt-4 border-t border-white/10 font-mono text-[11px] text-slate-400">
                    {node.tech}
                  </div>
                </div>
              ))}
            </div>

            {/* Bottom Verification Note */}
            <div className="mt-10 p-4 rounded-2xl bg-white/5 border border-white/10 flex flex-col sm:flex-row items-center justify-between font-mono text-xs text-slate-300 gap-4">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-emerald-400" />
                <span>100% PRODUCTION DEPLOYED & TESTED</span>
              </div>
              <div className="text-cyber-cyan">
                VIEW SOURCE ON GITHUB: github.com/Ashik-Siddike
              </div>
            </div>
          </motion.div>
        )}

      </motion.div>
    </section>
  );
}
